server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

spring:
  application:
    name: gateway-service
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/api/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/api/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/api/reissue
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/api/post/recommend
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/api/post/my
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/api/post
            - Method=POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/api/post/status
            - Method=PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/send
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/api/chat/rooms
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/api/chat/createroom
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/api/chat
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/ws-stomp
            - Method=*
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/sub/**
            - Method=*
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/pub/**
            - Method=*
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka